spring:
  datasource:
    username: root
    password: Dolphin880#
    url: jdbc:mysql://localhost:3306/serverdb
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
